# Generated by Django 5.1.4 on 2024-12-14 05:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.TextField(max_length=30)),
                ('first_name', models.TextField(max_length=30)),
                ('elo', models.IntegerField(default=1400)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moves', models.TextField(max_length=3000)),
                ('total_moves', models.IntegerField()),
                ('eco', models.TextField(max_length=3)),
                ('result', models.TextField(max_length=7)),
                ('date', models.DateField()),
                ('location', models.TextField(max_length=50)),
                ('pgn', models.TextField(max_length=100)),
                ('black_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='black_player', to='games.player')),
                ('white_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='white_player', to='games.player')),
            ],
        ),
    ]
