# Generated by Django 5.1.4 on 2024-12-14 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_result_remove_game_eco_remove_game_total_moves_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='pgn',
            field=models.TextField(max_length=100, null=True),
        ),
    ]
