# Generated by Django 5.1.4 on 2024-12-16 05:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_alter_game_pgn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='elo',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4000)]),
        ),
    ]
